### ISSUE TITLE
Default path error

### ISSUE THREAD

**Issue by eliguori88** [eliguori88/restbrain-server#1]
When the default path is processed for a request to a non-existent path, the server sends the status code 503 by executing the logic of the default path API while it should execute the logic by sending the status code specified in the logic itself.
<br>
`[INFO ] 05/06/2021 15:21:04.904 - [/192.168.1.100:54133] [/192.168.1.100:80] - Connection enstablished
[TRACE] 05/06/2021 15:21:04.905 - Host: 192.168.1.100
[TRACE] 05/06/2021 15:21:04.905 - User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0
[TRACE] 05/06/2021 15:21:04.906 - Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
[TRACE] 05/06/2021 15:21:04.906 - Accept-Language: it-IT,it;q=0.8,en-US;q=0.5,en;q=0.3
[TRACE] 05/06/2021 15:21:04.906 - Accept-Encoding: gzip, deflate
[TRACE] 05/06/2021 15:21:04.906 - Connection: keep-alive
[TRACE] 05/06/2021 15:21:04.907 - Upgrade-Insecure-Requests: 1
[TRACE] 05/06/2021 15:21:04.907 - 
[ERROR] 05/06/2021 15:21:04.907 - [/192.168.1.100:54133] [/192.168.1.100:80] - Path /pings not found, default operation: default
[ERROR] 05/06/2021 15:21:04.907 - [/192.168.1.100:54133] [/192.168.1.100:80] - Executing default path
[TRACE] 05/06/2021 15:21:04.908 - [Flow] Execution flow logic block: class it.gexy.restbrain.server.core.logic.blocks.LBText
[TRACE] 05/06/2021 15:21:04.908 - [Logic block Text] Payload in: default
[TRACE] 05/06/2021 15:21:04.908 - [Logic blocK Text] Text: default
[TRACE] 05/06/2021 15:21:04.909 - [Logic block Text] Payload out: default
[TRACE] 05/06/2021 15:21:04.909 - [Flow] Execution flow logic block: class it.gexy.restbrain.server.core.logic.blocks.http.LBResponce
[TRACE] 05/06/2021 15:21:04.909 - [Logic block Responce] Payload in: default
[TRACE] 05/06/2021 15:21:04.909 - [Logic block Responce] Set status code to: 200
[DEBUG] 05/06/2021 15:21:04.909 - [Logic block Responce] Set responce type to: text/json
[DEBUG] 05/06/2021 15:21:04.910 - [Logic block Responce] Sending responce
java.net.SocketException: Connection reset by peer
[ERROR] 05/06/2021 15:21:04.911 - [/192.168.1.100:54133] [/192.168.1.100:80] - java.net.SocketException: Connection reset by peer, trying to send internal server error responce...
[DEBUG] 05/06/2021 15:21:04.911 - HTTP/1.1 500 Internal server error

[ERROR] 05/06/2021 15:21:04.911 - [/192.168.1.100:54133] [/192.168.1.100:80] - java.net.SocketException: Connection reset by peer
	at java.base/sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:420)
	at java.base/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:440)
	at java.base/sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:826)
	at java.base/java.net.Socket$SocketOutputStream.write(Socket.java:1051)
	at java.base/java.io.OutputStream.write(OutputStream.java:127)
	at it.gexy.restbrain.server.core.server.http.HTTPResponce.send(HTTPResponce.java:47)
	at it.gexy.restbrain.server.core.server.http.SocketHandler.run(SocketHandler.java:224)
	at java.base/java.lang.Thread.run(Thread.java:832)
java.net.SocketException: Connection reset by peer
	at java.base/sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:420)
	at java.base/sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:440)
	at java.base/sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:826)
	at java.base/java.net.Socket$SocketOutputStream.write(Socket.java:1051)
	at java.base/java.io.OutputStream.write(OutputStream.java:127)
	at it.gexy.restbrain.server.core.server.http.SocketHandler.respond(SocketHandler.java:66)
	at it.gexy.restbrain.server.core.server.http.SocketHandler.run(SocketHandler.java:241)
	at java.base/java.lang.Thread.run(Thread.java:832)
[INFO ] 05/06/2021 15:21:04.940 - [/192.168.1.100:54134] [/192.168.1.100:80] - Connection enstablished
[DEBUG] 05/06/2021 15:21:04.942 - HTTP/1.1 500 Unable to parse request`

**Comment by eliguori88** [comment]
There was a remnant of the earliest versions, where the Responce.send () was called manually and not by executing logic
